name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch: # Allows manual trigger
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation (transparent background & cooler colors)
        uses: Platane/snk@v3
        with:
          github_user_name: JohnCarlosSebuco
          outputs: |
            dist/github-snake.svg?background=transparent&color_snake=#00BFFF&color_dots=#1E90FF,#00CED1,#40E0D0,#87CEFA
            dist/github-snake.gif?background=transparent&color_snake=#00BFFF&color_dots=#1E90FF,#00CED1,#40E0D0,#87CEFA

      - name: Push generated files to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions[bot]
          author_email: github-actions[bot]@users.noreply.github.com
          message: "Generate snake animation"
          add: "dist"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
